config/routes.rb
Rails.application.routes.draw do
  resources :categories do 
    resources :payments
  end
  devise_for :users
  devise_scope :user do
    get '/logout', to: 'devise/sessions#destroy'
  end  
  root to: 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    return unless user.present?

    can :manage, Category, user_id: user.id
    can :manage, Payment, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :icon, presence: true

  def total_transaction_amount
    payments.sum(:amount)
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_many :category, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :amount, presence: true, numericality: { greater_than: 0, only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :categories
  has_many :payments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.includes(:payments).where(user_id: current_user.id).order(updated_at: :desc)
  end

  # GET /categories/1 or /categories/1.json
  def show
    redirect_to new_category_payment_path(@category)
  end

  # GET /categories/new
  def new
    @category = current_user.categories.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]

  # GET /payments or /payments.json
  def index
    @category = Category.find(params[:category_id])
    @payments = Payment.where(user: current_user, category_id: @category.id).order(updated_at: :desc)
    @total = Payment.where(user: current_user, category_id: @category.id).sum(:amount)
  end

  # GET /payments/1 or /payments/1.json
  def show
    @category = Category.find(params[:category_id])
    @payment = Payment.find(params[:id])
  end

  # GET /payments/new
  def new
    @category = Category.find(params[:category_id])
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)
    @payment.user_id = current_user.id
    category = Category.find(params[:category_id])
    @payment.category_id = category.id

    respond_to do |format|
      if @payment.save
        format.html { redirect_to category_payments_url(@payment), notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Icon:</strong>
    <%= category.icon %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
<div class="header reg-head">
<a href="<%= categories_path %>">
  <i class="fa-solid fa-arrow-left"></i>
  </a>
  <p>NEW CATEGORY</p>
    <%= form.submit "Create", class: "reg-next" %>
</div>
<div class="form-container">

    <%= form.text_field :name, placeholder: "Name" %>

    <%= form.text_field :icon, placeholder: "Icon Link" %>

  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="header reg-head">
<i class="fa-solid fa-bars"></i>
  <p>CATEGORIES</p>
  <a href="/logout" data-method="delete">
 <i class="fa-solid fa-arrow-right-from-bracket"></i>
  </a>
</div>


<div id="categories-container">

<% if @categories.empty? %>
      <div class="empty-message">You have not added any Category. Add one by clicking the button below.</div>
    <% else %> <% @categories.each do |category| %>

  <a href="<%= category_payments_path(category.id) %>">

    <div class="single-category">
      <img src="<%= category.icon %>" alt="icon" class="category-icon">
      <p class="category-name"><%= category.name %></p>
      <p class="category-total"> $ <%= category.total_transaction_amount %> </p>
    </div>
    
  </a>

  <% end %>
  <% end %>

  <div class="green-btn">
    <%= link_to "NEW CATEGORY", new_category_path %>
  </div>

</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
  <%= link_to "Back to categories", categories_path %>


<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="splash-container">
<h1 class="splash-logo">PennyPincher</h1>


<div class="splash-btns">
    <%= button_to "LOG IN" , new_user_session_path, class: "login-btn" %>
    <%= link_to "SIGN UP" , new_user_registration_path, class: "btn btn-primary" %>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PennyPincher</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, url: category_payments_path) do |form| %>
<div class="header reg-head">
<a href="<%= category_payments_path %>">
  <i class="fa-solid fa-arrow-left"></i>
  </a>
  <p>NEW TRANSACTION</p>
    <%= form.submit "Create", class: "reg-next" %>
</div>
<div class="form-container">

    <%= form.text_field :name, placeholder: "Name" %>

    <%= form.text_field :amount, placeholder: "Amount" %>

  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<div class="header reg-head">
<a href="<%= categories_path %>">
  <i class="fa-solid fa-arrow-left"></i>
  </a>
  <p>TRANSACTIONS</p>
  <a href="/logout" data-method="delete">
 <i class="fa-solid fa-arrow-right-from-bracket"></i>
  </a>
</div>



<div id="payments">

<% if @payments.empty? %>
      <div class="empty-message">There are no Transactions for this category. Add one by clicking the button below.</div>
    <% else %>
  <% @payments.each do |payment| %>
  <div class="single-payment">
      <p class="payment-name"><%= payment.name %></p>
      <p> $ <%= payment.amount %> </p>
    </div>
  <% end %>
  <% end %>

 <div class="green-btn">
    <%= link_to "NEW TRANSACTION", new_category_payment_path %>
  </div>

</div>

app/views/payments/new.html.erb
<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>